name: Django_Test

on:
  push:
    branches: [ "test" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Update code & Deploy
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.REMOTE_IP }}
        username: ${{ secrets.REMOTE_USER }}
        key: "${{ secrets.MAKEBFFS }}"
        port: ${{ secrets.REMOTE_SSH_PORT }}
        script: |
          echo "${{secrets.MAKEBFFS}}" >> $HOME/makebffs.pem
          chmod 600 $HOME/makebffs.pem
          ssh -i $HOME/makebffs.pem -o StrictHostKeyChecking=no ubuntu@ec2-13-125-60-48.ap-northeast-2.compute.amazonaws.com 
          '
          ls &&
          cd /home/ubuntu/backend/django/ &&
          ls &&
          git pull origin main &&
          cd /home/ubuntu/ &&
          sudo docker compose up --build -d &&
          sudo docker compose restart
          '
