name: Django_Test

on:
  push:
    branches: [ "main","development" ]
  pull_request:
    branches: [ "main","development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        export PATH="$HOME/.poetry/bin:$PATH"
        poetry install --no-root

    - name: Set up environment variables
      run: |
        echo "SECRET_KEY='${{ secrets.SECRET_KEY }}'" >> .env 
        echo "EMAIL='${{ secrets.EMAIL }}'" >> .env
        echo "EMAIL_PASSWORD='${{ secrets.EMAIL_PASSWORD }}'" >> .env

    - name: Run Tests with environment variables
      run: |
        source .env  # Load environment variables from .env file
        poetry run python manage.py makemigations
        poetry run python manage.py migrate
        poetry run python manage.py test
